name: Release

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.12.0"

      - name: Setup pnpm
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
        uses: pnpm/action-setup@v4.0.0
        with:
          # Version of pnpm to install
          version: 9.15.2 # optional

      - name: Install NPM Dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create Version PR or Publish to NPM
        id: changesets
        uses: changesets/action@v1.4.9
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: node .github/changeset-version.js
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: "production"
